engines:
  rubocop:
    enabled: true
  reek:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        javascript
ratings:
   paths:
   - Gemfile.lock
   - "**.rb"
   - "**.md"

exclude_paths:
- "test/**/*"
- "docs/**/*"
