language: node_js

node_js:
  - 10.19.0

before_install:
  - npm install -g npm@6.14.4

install:
  - npm install

script:
  - npm run coverage

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"